# Generated by Django 6.1 on 2026-08-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_loginauditlog_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Waiter', 'Waiter'), ('Kitchen', 'Kitchen'), ('Customer', 'Customer')], default='Waiter', max_length=50),
        ),
    ]
