# Generated by Django 6.0.7 on 2026-08-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_order_i_3d4604_idx',
            old_name='payments_order_status_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentproof',
            new_name='payment_pro_verific_58cd39_idx',
            old_name='payment_proof_status_idx',
        ),
    ]
