# Generated by Django 5.2.17 on 2026-08-20 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentproof',
            name='payment_pro_verific_58cd39_idx',
        ),
        migrations.RemoveField(
            model_name='paymentproof',
            name='review_note',
        ),
        migrations.RemoveField(
            model_name='paymentproof',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='paymentproof',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='paymentproof',
            name='verification_status',
        ),
        migrations.AddIndex(
            model_name='paymentproof',
            index=models.Index(fields=['submitted_at'], name='payment_pro_submitt_c724e9_idx'),
        ),
    ]
