# Generated by Django 6.1 on 2026-08-21 16:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('raw', 'Raw Ingredient'), ('processed', 'Processed'), ('packaging', 'Packaging'), ('cleaning', 'Cleaning')], default='raw', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('min_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Low-stock alert threshold', max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
