# Generated by Django 6.0.7 on 2026-08-15 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIssue',
            fields=[
                ('issue_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('WRONG_ITEM', 'Wrong item'), ('MISSING_ITEM', 'Missing item'), ('LATE_ORDER', 'Late order'), ('CUSTOMER_COMPLAINT', 'Customer complaint'), ('PAYMENT_ISSUE', 'Payment issue'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='orders.order')),
                ('reported_by', models.ForeignKey(db_column='reported_by_id', on_delete=django.db.models.deletion.PROTECT, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_issues',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='order_issues_order_ts_idx')],
            },
        ),
    ]
